
export const arrayItems =[
    {
        id: 1,
        tittle: 'lampara 1',
        imgUrl: "./multimedia/img/lampara1.jpg",
        categoria: ["escritorio"],
        stock: 5,
        price: 5820,
        detalle: 'ñonñonñon',
    },
    {
        id: 2,
        tittle: 'lampara 2',
        imgUrl: './multimedia/img/lampara2.jpg',
        categoria: ["escritorio"],
        stock: 8,
        price: 6040,
        detalle: 'ñonñonñon',
    },
    {
        id: 3,
        tittle: 'lampara 3',
        imgUrl: './multimedia/img/lampara3.jpg',
        categoria: ["escritorio"],
        stock: 10,
        price: 6790,
        detalle: 'ñonñonñon',
    },
    


    {
        id: 4,
        tittle: "lampara 4 ",
        imgUrl: './multimedia/img/lampara4.jpg',
        categoria: ["escritorio"],
        stock: 5,
        price: 3095,
        detalle: 'ñonñonñon',
    },
    {
        id: 6,
        tittle: "lampara 6",
        imgUrl: './multimedia/img/lampara6.jpg',
        categoria: ["lampara de pie"],
        portada: false,
        stock: 10,
        price: 4899,
        detalle: 'ñonñonñon',
    },
    {
        id: 6,
        tittle: "lampara 6",
        imgUrl: './multimedia/img/lampara6.jpg',
        categoria: ["lampara de pie"],
        portada: false,
        stock: 10,
        price: 4899,
        detalle: 'ñonñonñon',
    },
    {
        id: 6,
        tittle: "lampara 6",
        imgUrl: './multimedia/img/lampara6.jpg',
        categoria: ["lampara de pie"],
        portada: false,
        stock: 10,
        price: 4899,
        detalle: 'ñonñonñon',
    },
    {
        id: 6,
        tittle: "lampara 6",
        imgUrl: './multimedia/img/lampara6.jpg',
        categoria: ["lampara de pie"],
        portada: false,
        stock: 10,
        price: 4899,
        detalle: 'ñonñonñon',
    },
    {
        id: 6,
        tittle: "lampara 6",
        imgUrl: './multimedia/img/lampara6.jpg',
        categoria: ["lampara de pie"],
        portada: false,
        stock: 10,
        price: 4899,
        detalle: 'ñonñonñon',
    },
    {
        id: 6,
        tittle: "lampara 6",
        imgUrl: './multimedia/img/lampara6.jpg',
        categoria: ["lampara de pie"],
        portada: false,
        stock: 10,
        price: 4899,
        detalle: 'ñonñonñon',
    },
    {
        id: 6,
        tittle: "lampara 6",
        imgUrl: './multimedia/img/lampara6.jpg',
        categoria: ["lampara de pie"],
        portada: false,
        stock: 10,
        price: 4899,
        detalle: 'ñonñonñon',
    },
]
