
export const arrayItems =[
    {
        id: 1,
        tittle: 'lampara 1',
        imgUrl: "./multimedia/img/lampara1.jpg",
        categoria: ["escritorio"],
        stock: 5,
        price: 5820,
        detalle: 'ñonñonñon',
    },
    {
        id: 2,
        tittle: 'lampara 2',
        imgUrl: './multimedia/img/lampara2.jpg',
        categoria: ["escritorio"],
        stock: 8,
        price: 6040,
        detalle: 'ñonñonñon',
    },
    {
        id: 3,
        tittle: 'lampara 3',
        imgUrl: './multimedia/img/lampara3.jpg',
        categoria: ["escritorio"],
        stock: 10,
        price: 6790,
        detalle: 'ñonñonñon',
    },
    {
        id: 4,
        tittle: "lampara 4 ",
        imgUrl: './multimedia/img/lampara4.jpg',
        categoria: ["escritorio"],
        stock: 5,
        price: 3095,
        detalle: 'ñonñonñon',
    },
    {
        id: 5,
        tittle: "lampara 5",
        imgUrl: './multimedia/img/lampara5.jpg',
        categoria: ["lampara de pie"],
        portada: false,
        stock: 10,
        price: 4899,
        detalle: 'ñonñonñon',
    },
    {
        id: 6,
        tittle: "lampara 6",
        imgUrl: './multimedia/img/lampara6.jpg',
        categoria: ["lampara de pie"],
        portada: false,
        stock: 10,
        price: 4899,
        detalle: 'ñonñonñon',
    },
    {
        id: 7,
        tittle: "lampara 7",
        imgUrl: './multimedia/img/lampara7.jpg',
        categoria: ["lampara de pie"],
        portada: false,
        stock: 10,
        price: 4899,
        detalle: 'ñonñonñon',
    },
    {
        id: 8,
        tittle: "lampara 8",
        imgUrl: './multimedia/img/lampara8.jpg',
        categoria: ["lampara de pie"],
        portada: false,
        stock: 10,
        price: 4899,
        detalle: 'ñonñonñon',
    },
    {
        id: 9,
        tittle: "lampara 9",
        imgUrl: './multimedia/img/lampara9.jpg',
        categoria: ["lampara de pie"],
        portada: false,
        stock: 10,
        price: 4899,
        detalle: 'ñonñonñon',
    },
    {
        id: 10,
        tittle: "lampara 10",
        imgUrl: './multimedia/img/lampara10.jpg',
        categoria: ["lampara de pie"],
        portada: false,
        stock: 10,
        price: 4899,
        detalle: 'ñonñonñon',
    },
    {
        id: 11,
        tittle: "lampara 11",
        imgUrl: './multimedia/img/lampara11.jpg',
        categoria: ["lampara de pie"],
        portada: false,
        stock: 10,
        price: 4899,
        detalle: 'ñonñonñon',
    },
]
