export let arrayItems =[
    {
    id: 1,
    nombre: 'lampara 1',
    img: "../multimedia/img/lampara1.jpg",
    categoria: "escritorio",
    portada: true,
    stock: 5,
    precio: 5820,
    descripcion: 'ñonñonñon',
    },
    {
    id: 2,
    nombre: 'lampara 2',
    img: "../multimedia/img/lampara2.jpg",
    categoria: "escritorio",
    portada: false,
    stock: 8,
    precio: 6040,
    descripcion: 'ñonñonñon',
    },
    {
    id: 3,
    nombre: 'lampara 3',
    img: "../multimedia/img/lampara3.jpg",
    categoria: "escritorio",
    portada: true,
    stock: 5,
    precio: 5040,
    descripcion: 'ñonñonñon',
    },
    {
    id: 4,
    nombre: 'lampara 4',
    img: "../multimedia/img/lampara4.jpg",
    categoria: "escritorio",
    portada: false,
    stock: 8,
    precio: 7040,
    descripcion: 'ñonñonñon',
    },
    {
    id: 5,
    nombre: 'lampara 5',
    img: "../multimedia/img/lampara5.jpg",
    categoria: "lampara de pie",
    portada: true,
    stock: 18,
    precio: 16040,
    descripcion: 'ñonñonñon',
    }
]
