const items2 =[
    {
        id: 1,
        tittle: "DISCO DURO HDD 1TB SEAGATE BARRACUDA SATA III",
        imgUrl: "./multimedia/img/1586464173_disc1.jpg",
        categoria: ["discosMecanicos"],
        portada: true,
        stock: 5,
        price: 5820,
    },
    {
        id: 2,
        tittle: "DISCO DURO HDD 1 TB WESTERN DIGITAL WD BLUE",
        imgUrl: "multimedia/img/1586464173_disc1.jpg",
        categoria: ["discosMecanicos"],
        portada: false,
        stock: 8,
        price: 6040,
    },
    {
        id: 3,
        tittle: "DISCO DURO HDD 1 TB WESTERN DIGITAL WD SATA III 64MB/S PURPLE",
        imgUrl: "multimedia/img/1586464173_disc1.jpg",
        categoria: ["discosMecanicos"],
        portada: false,
        stock: 10,
        price: 6790,
    },
    {
        id: 4,
        tittle: "DISCO SOLIDO SSD 120GB ADATA SATA III SU650",
        imgUrl: "multimedia/img/1586464173_disc1.jpg",
        categoria: ["discosSolidos"],
        portada: false,
        stock: 5,
        price: 3095,
    },
    {
        id: 5,
        tittle: "DISCO SOLIDO SSD 120GB GIGABYTE SATA III GP-GSTF",
        imgUrl: "multimedia/img/1586464173_disc1.jpg",
        categoria: ["discosSolidos"],
        portada: true,
        stock: 8,
        price: 3199,
    },    
]
